const questionWords = [
    `?`,
    `why`,
    `which`,
    `when`,
    `what`,
    `how`,
    `where`,
    `who`,
    `should i`,
    `can you`,
    `can u`,
    `do the`,
    `do you`,
    `is it`,
    `could you`,
    `could i`,
    `would you`,
    `would i`,
    `shall i`,
    `will you`,
    `will i`,
    `am i`,
    `are you`,
    `have you`,
    `have i`,
    `did you`,
    `did i`,
    `what if`,
    `may i`,
    `might i`,
    `shouldn't i`,
    `won't you`,
    `won't i`,
    `aren't you`,
    `was i`,
    `were you`,
    `must i`,
    `must you`,
    `is there`,
    `couldn't you`,
    `does it`,
    `do they`,
    `does he`,
    `does she`,
    `can they`,
    `can he`,
    `can she`,
    `shall we`,
    `are we`,
    `is this`,
    `is that`,
    `what's the`,
    `why do i`,
    `isn't it`,
    `wasn't it`,
    `doesn't it`,
    `don't you`,
    `don't they`,
    `didn't you`,
    `didn't they`,
    `haven't you`,
    `haven't they`,
    `what kind`,
    `who can`,
    `who should`,
    `who will`
  ];

  module.exports = {
    questionWords 
  };